# Generated by Django 2.1.5 on 2019-01-20 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('secret_key', models.CharField(max_length=100)),
                ('merchid', models.CharField(max_length=100)),
                ('submittext', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cause',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('starter_price', models.PositiveIntegerField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rajksimple.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_acc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rajksimple.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('repetition', models.IntegerField(choices=[(0, 'Egyszeri'), (1, 'Havonta'), (3, 'Negyedévente'), (6, 'Félévente'), (12, 'Évente')], default=0)),
                ('token', models.CharField(blank=True, max_length=200, null=True)),
                ('cause', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rajksimple.Cause')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='default_cause',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='default_cause', to='rajksimple.Cause'),
        ),
    ]
